<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZogQq4u\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZogQq4u/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZogQq4u.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZogQq4u\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZogQq4u\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZogQq4u',
    'container.build_id' => '5ffb80b0',
    'container.build_time' => 1696100414,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZogQq4u');
