<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM8n4UGu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM8n4UGu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM8n4UGu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM8n4UGu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerM8n4UGu\App_KernelDevDebugContainer([
    'container.build_hash' => 'M8n4UGu',
    'container.build_id' => '58e83ce6',
    'container.build_time' => 1695431333,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM8n4UGu');
